sudo: false
language: ruby
rvm:
  - 2.3.3
before_install:
  - gem install bundler -v 1.13.6
  - openssl aes-256-cbc -K $encrypted_22290c477736_key -iv $encrypted_22290c477736_iv -in config/service_account.json.enc -out config/service_account.json -d

