sudo: false
language: ruby
rvm:
  - 2.3.3
before_install:
  - gem install bundler -v 1.13.6
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_key -in config/service_account.json.enc -out config/service_account.json -d

